# Generated by Django 4.2.3 on 2023-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
    
