# Generated by Django 4.2.3 on 2023-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_task_completed_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
