# Generated by Django 4.2.3 on 2023-12-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_status_name_alter_task_status'),
    ]

    operations = [
    ]
