# Generated by Django 4.2.3 on 2023-12-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_task_assigned_to_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
