# Generated by Django 4.2.3 on 2024-01-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
