# Generated by Django 4.2.3 on 2024-01-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_task_submitted_to_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='submitted_to_admin',
        ),
        migrations.AddField(
            model_name='task',
            name='submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
