# Generated by Django 4.2.3 on 2024-01-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userpermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
