# Generated by Django 4.2.3 on 2024-01-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_group_id_alter_permission_id_alter_user_id'),
        ('home', '0019_delete_userpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
