# Generated by Django 4.2.3 on 2024-01-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_userprofile_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
    ]
